<Project Sdk="Remora.Sdk">

	<PropertyGroup>
		<LibraryFrameworks>net8.0;net9.0</LibraryFrameworks>
		<TargetNetStandard>false</TargetNetStandard>
		<VersionPrefix>0.1.0</VersionPrefix>
		<Description>Provides Aspire integration for Zitadel</Description>
		<PackageReleaseNotes>Initial Release.</PackageReleaseNotes>
		<PackageTags>$(PackageTags);Zitadel;IDP</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Zitadel" />
	</ItemGroup>

</Project>
