<Project Sdk="Remora.Sdk">

  <PropertyGroup>
	  <LibraryFrameworks>net8.0;net9.0</LibraryFrameworks>
	  <TargetNetStandard>false</TargetNetStandard>
	  <VersionPrefix>0.1.0</VersionPrefix>
	  <Description>Provides service defaults.</Description>
	  <PackageReleaseNotes>Initial Release.</PackageReleaseNotes>
	  <PackageTags>$(PackageTags);Data;</PackageTags>
    <IsAspireSharedProject>true</IsAspireSharedProject>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    <PackageReference Include="Serilog" />
	<PackageReference Include="Serilog.Settings.Configuration" />
  </ItemGroup>

</Project>
