<Project Sdk="Remora.Sdk">

  <PropertyGroup>
    <LibraryFrameworks>net8.0;net9.0</LibraryFrameworks>
	  <TargetNetFramework>false</TargetNetFramework>
	  <VersionPrefix>0.1.0</VersionPrefix>
	  <Description>Provides a set of base types for the data library.</Description>
	  <PackageReleaseNotes>Initial Release.</PackageReleaseNotes>
	  <PackageTags>$(PackageTags);Data;Abstractions;</PackageTags>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
