name: .NET Test

env:
  GITHUB_USER: LuzFaltex
  GITHUB_FEED: https://nuget.pkg.github.com/LuzFaltex
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  - pull_request
  - workflow_dispatch

jobs:
  build:
    strategy: 
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: Build
        run: |
          dotnet restore
          dotnet build -c Debug
          
      - name: Test
        run: dotnet test -c Debug --no-restore --no-build --verbosity minimal